#############################################################################
# Makefile for building: wcalc
# Generated by qmake (3.1) (Qt 5.15.1)
# Project:  wcalc.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile wcalc.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = wcalc1.0.0
DISTDIR = /Users/denis/Desktop/Work/wcalc_expression_parser/.tmp/wcalc1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS)    
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		kernel.cpp 
OBJECTS       = main.o \
		kernel.o
DIST          = /usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/lex.prf \
		wcalc.pro kernel.h main.cpp \
		kernel.cpp
QMAKE_TARGET  = wcalc
DESTDIR       = 
TARGET        = wcalc

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/denis/Desktop/Work/wcalc_expression_parser/wcalc.pro


include /usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

wcalc:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: wcalc.pro /usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/lex.prf \
		wcalc.pro
	$(QMAKE) -o Makefile wcalc.pro
/usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/lex.prf:
wcalc.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile wcalc.pro

qmake_all: FORCE


all: Makefile wcalc

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

check: first

benchmark: first

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp kernel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

kernel.o: kernel.cpp kernel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kernel.o kernel.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/wcalc/bin || mkdir -p $(INSTALL_ROOT)/opt/wcalc/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/wcalc/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/wcalc/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/wcalc/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/wcalc/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

